---

#  Gerenciamento de pacotes e atualização do Sistema Operacional

- name: Atualização do Sistema Operacional
  apt: name=* state=latest update_cache=yes

- name: Instalação de Pacotes
  apt: 
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - curl
      - jq   #  a Linux command line utility that is easily used to extract data from JSON documents
      - ruby-full
      - software-properties-common
      - python3.8
      - python3-venv 
      - python3-pip
      - influxdb-client
      - apt-transport-https 
      - ca-certificates
      - unzip

- name: Baixando AWSCLI 2
  command: curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip

- name: Extraindo Aquivo AWSCLI 2
  command: unzip awscliv2.zip

- name: Instalando AWSCLI 2
  command: ./aws/install
...